(require 'ert)
(require 'sid64-starlark-mode)
(ert-deftest sid64-highlighting ()
  (with-temp-buffer
    (insert "# tell in comment\nroom(\"monster in string\")\ndef on_enter(event):\n    tell(event.text)\n")
    (sid64-starlark-mode)
    (font-lock-ensure)
    (should (= python-indent-offset 4))
    (goto-char (point-min))
    (search-forward "tell")
    (should (eq (get-text-property (1- (point)) 'face) 'font-lock-comment-face))
    (search-forward "room")
    (should (eq (get-text-property (1- (point)) 'face) 'font-lock-builtin-face))
    (search-forward "monster")
    (should (eq (get-text-property (1- (point)) 'face) 'font-lock-string-face))))
(ert-run-tests-batch-and-exit)
