<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>SID64 Starlark</string>
	<key>scopeName</key>
	<string>source.sid64-starlark</string>
	<key>fileTypes</key>
	<array>
		<string>star</string>
	</array>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment.line.number-sign.starlark</string>
			<key>match</key>
			<string>#.*$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.triple.starlark</string>
			<key>begin</key>
			<string>\b[rR]"""</string>
			<key>end</key>
			<string>"""</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.triple.starlark</string>
			<key>begin</key>
			<string>\b[rR]'''</string>
			<key>end</key>
			<string>'''</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.single.starlark</string>
			<key>begin</key>
			<string>\b[rR]"</string>
			<key>end</key>
			<string>"|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.single.starlark</string>
			<key>begin</key>
			<string>\b[rR]'</string>
			<key>end</key>
			<string>'|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.triple.starlark</string>
			<key>begin</key>
			<string>"""</string>
			<key>end</key>
			<string>"""</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.starlark</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.triple.starlark</string>
			<key>begin</key>
			<string>'''</string>
			<key>end</key>
			<string>'''</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.starlark</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.single.starlark</string>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.starlark</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.single.starlark</string>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.starlark</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.hook.sid64</string>
			<key>match</key>
			<string>\b(?:on_enter|on_look|on_say|on_command|on_talk|on_use)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(def)\s+([A-Za-z_]\w*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.starlark</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.starlark</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.sid64</string>
			<key>match</key>
			<string>(?&lt;!\.)\b(?:room|link|monster|tell|say|get_state|set_state|award_gold|heal)\b(?=\s*\()</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.builtin.starlark</string>
			<key>match</key>
			<string>(?&lt;!\.)\b(?:abs|all|any|bool|bytes|chr|dict|dir|enumerate|fail|float|getattr|hasattr|hash|int|len|list|max|min|ord|range|repr|reversed|sorted|str|tuple|type|zip)\b(?=\s*\()</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.starlark</string>
			<key>match</key>
			<string>\b(?:and|break|continue|def|elif|else|for|if|in|lambda|not|or|pass|return)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.starlark</string>
			<key>match</key>
			<string>\b(?:True|False|None)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.other.property.sid64</string>
			<key>match</key>
			<string>(?&lt;=\.)\b(?:player|room|target|id|name|kind|command|text)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.starlark</string>
			<key>match</key>
			<string>\b(?:0[xX][0-9a-fA-F]+|0[oO][0-7]+|0[bB][01]+|[0-9]+(?:\.[0-9]*)?(?:[eE][+-]?[0-9]+)?)\b|(?&lt;!\w)\.[0-9]+(?:[eE][+-]?[0-9]+)?\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.starlark</string>
			<key>match</key>
			<string>[-+*/%=&lt;&gt;!&amp;|^~]+</string>
		</dict>
		<dict>
			<key>name</key>
			<string>punctuation.section.starlark</string>
			<key>match</key>
			<string>[()\[\]{}]</string>
		</dict>
	</array>
</dict>
</plist>
