" Generated by editors/tools/build.py; edit language.json or the generator.
if exists('b:current_syntax') | finish | endif
syntax case match
syntax sync fromstart
syntax match sid64Comment "#.*$"
syntax match sid64Number "\<\d\+\(\.\d*\)\?\([eE][+-]\?\d\+\)\?\>"
syntax match sid64Number "\<0[xX][0-9a-fA-F]\+\>"
syntax region sid64String start=+"+ skip=+\\.+ end=+"+ oneline
syntax region sid64String start=+'+ skip=+\\.+ end=+'+ oneline
syntax region sid64String start=+"""+ skip=+\\.+ end=+"""+
syntax region sid64String start=+'''+ skip=+\\.+ end=+'''+
syntax match sid64Function "\<def\s\+\zs\h\w*"
syntax keyword sid64Keyword and break continue def elif else for if in lambda not or pass return
syntax keyword sid64Constant True False None
syntax keyword sid64API room link monster tell say get_state set_state award_gold heal
syntax keyword sid64Builtin abs all any bool bytes chr dict dir enumerate fail float getattr hasattr hash int len list max min ord range repr reversed sorted str tuple type zip
syntax keyword sid64Hook on_enter on_look on_say on_command on_talk on_use
highlight default link sid64Comment Comment
highlight default link sid64Number Number
highlight default link sid64String String
highlight default link sid64Function Function
highlight default link sid64Keyword Keyword
highlight default link sid64Constant Constant
highlight default link sid64API Function
highlight default link sid64Builtin Function
highlight default link sid64Hook Special
let b:current_syntax = 'sid64starlark'
