ALTER TABLE npcs
 ADD COLUMN hostile BOOLEAN NOT NULL DEFAULT false,
 ADD COLUMN attack_damage INTEGER NOT NULL DEFAULT 0 CHECK (attack_damage BETWEEN 0 AND 100),
 ADD COLUMN defense INTEGER NOT NULL DEFAULT 0 CHECK (defense BETWEEN 0 AND 50),
 ADD COLUMN reward_gold INTEGER NOT NULL DEFAULT 0 CHECK (reward_gold BETWEEN 0 AND 100),
 ADD COLUMN reward_experience INTEGER NOT NULL DEFAULT 0 CHECK (reward_experience BETWEEN 0 AND 1000),
 ADD COLUMN respawn_seconds INTEGER NOT NULL DEFAULT 300 CHECK (respawn_seconds BETWEEN 30 AND 3600),
 ADD COLUMN respawn_at TIMESTAMPTZ;
